full_name = input("Enter your full name: ")
age = int(input("Enter your age: "))
birthday = int(input("Enter your birthday: "))
year_level = input("Enter your year level (in words): ")
program = input("Enter your program: ")
section = int(input("Enter your section: "))
